Feb 11, 2025 4:55:45 PM task9.threads.runner.ThreadRunner main
SEVERE: Exception caught in main method: null
